version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - greenhouse-network

  dbapi:
    build:
      context: ./DBAPI
      dockerfile: Dockerfile
    container_name: dbapi
    ports:
      - "7000:80"
    networks:
      - greenhouse-network
    depends_on:
      - mongo

  backendapi:
    build:
      context: ./BackEndAPI
      dockerfile: Dockerfile
    container_name: backendapi
    ports:
      - "5047:80"
    networks:
      - greenhouse-network
    depends_on:
      - dbapi

  iotcontroller:
<<<<<<< Updated upstream
    build:
      context: .
      dockerfile: IOTController/Dockerfile
    container_name: iotcontroller
    ports:
      - "50000:50000"
      - "6000:6000"
=======
    image: javieruw/iotcontroller:latest
    build:
      context: ./IOTController
      dockerfile: Dockerfile
    container_name: iotcontroller
    ports:
      - "6000:6000"
      - "50000:50000"
>>>>>>> Stashed changes
    networks:
      - greenhouse-network
    depends_on:
      - backendapi

networks:
  greenhouse-network:
    driver: bridge
