
version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - greenhouse-network

  dbapi:
    build:
      context: .
      dockerfile: DBAPI/Dockerfile
    container_name: dbapi
    ports:
      - "7000:80"
    networks:
      - greenhouse-network
    depends_on:
      - mongo

  frontendcontroller:
    build:
      context: .
      dockerfile: FrontEndController/Dockerfile
    container_name: frontendcontroller
    ports:
      - "5047:80"
    networks:
      - greenhouse-network
    depends_on:
      - dbapi

  iotcontroller:
    build:
      context: .
      dockerfile: IOTController/Dockerfile
    container_name: iotcontroller
    ports:
      - "50000:50001"
      - "6000:6000"
    networks:
      - greenhouse-network
    depends_on:
      - frontendcontroller

networks:
  greenhouse-network:
    driver: bridge