name: Docker Compose CI/CD

on:
  push:
    branches: [ Deployment ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: javieruw
        password: AsSoonAsYouAreAble

    - name: Build with Docker Compose
      run: docker-compose build

    - name: Push Images (Optional)
      run: |
        docker-compose push dbapi:latest
        docker-compose push backendapi:latest
        docker-compose push iotcontroller:latest

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: 154.62.108.77
        username: root
        password: Miraflores281  # or use 'key' if you prefer using SSH keys
        script: |
          docker tag dbapi https://hub.docker.com/repository/docker/javieruw/dbapi:latest
          docker tag backendapi https://hub.docker.com/repository/docker/javieruw/backendapi:lates
          docker tag iotcontroller https://hub.docker.com/repository/docker/javieruw/iotcontroller:latest
          cd /root/BackEnd
          docker-compose down
          docker-compose rm -f
          docker-compose up -d