name: Docker Compose CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker images
      run: docker-compose -f docker-compose.yml build --parallel

    - name: Run Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Wait for services to be ready
      run: |
        sleep 30
        docker-compose ps

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' # Adjust the .NET version as needed

    - name: Restore dependencies
      run: dotnet restore TestProject/TestProject.csproj

    - name: Build the test project
      run: dotnet build TestProject/TestProject.csproj --no-restore

    - name: Run tests
      run: dotnet test TestProject/TestProject.csproj --logger:trx

    - name: Stop Docker Compose
      if: always()
      run: docker-compose -f docker-compose.yml down
